<?php

/**
 * @file
 * Provides a nicer experience for Wildcat-flavored sites.
 */

use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_block_view_alter().
 */
function wildcat_block_view_alter(array &$build, BlockPluginInterface $block) {
  /** @var \Drupal\Core\Render\RendererInterface $renderer */
  $renderer = \Drupal::service('renderer');
  $renderer->addCacheableDependency($build, $block);

  // Always add block_view:BASE_PLUGIN_ID as a cache tag.
  $build['#cache']['tags'][] = 'block_view:' . $block->getBaseId();

  // If the plugin is a derivative, add block_view:FULL_PLUGIN_ID as well.
  if ($block->getDerivativeId()) {
    $build['#cache']['tags'][] = 'block_view:' . $block->getPluginId();
  }
}

/**
 * Implements template_preprocess_block().
 */
function wildcat_preprocess_block(array &$variables) {
  // Use the plugin id for the 'data-block-plugin-id' attribute.
  $plugin_id = $variables['elements']['#plugin_id'];
  $variables['attributes']['data-block-plugin-id'] = $plugin_id;
}

/**
 * Implements hook_entity_load().
 */
function wildcat_entity_load(array $entities) {
  /** @var \Drupal\wildcat\WildcatHelperInterface $helper */
  $helper = \Drupal::service('wildcat.helper.path_alias');
  // Make sure that a path alias is set for each entity.
  $helper->ensureEntitiesHavePathAlias($entities);
}
